services:
  proton:
    build:
      target: development
      context: .
      dockerfile: .pipeline/blubber.yaml
      args:
        LIVES_UID: $MW_DOCKER_UID
        LIVES_GID: $MW_DOCKER_GID
    volumes:
      - ./:/srv/service
    ports:
      - 3030:3030
    entrypoint: ""
    command: npm start
